export default [
	{
		languageOptions: {
			globals: {
				__dirname: 'readonly',
				module: 'readonly',
				require: 'readonly',
				document: 'readonly',
				window: 'readonly',
				console: 'readonly',
				URLSearchParams: 'readonly',
				history: 'readonly',
				alert: 'readonly',
			},
		},
		rules: {
			'array-bracket-spacing': ['error', 'never'],
			'arrow-parens': ['error', 'as-needed'],
			'arrow-spacing': 'error',
			'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
			'comma-dangle': [2, 'always-multiline'],
			'comma-spacing': ['error', { 'before': false, 'after': true }],
			'curly': 'error',
			'default-param-last': 'error',
			'dot-notation': 'error',
			'eol-last': ['error', 'never'],
			'eqeqeq': 'error',
			'for-direction': 'error',
			'func-name-matching': ['error', 'always'],
			'indent': ['error', 'tab'],
			'keyword-spacing': ['error', {
				'before': true,
				'after': true,
				'overrides': {
					'return': { 'after': true },
					'throw': { 'after': true },
					'case': { 'after': true },
				},
			}],
			'max-len': ['error', { 'code': 128, 'ignoreComments': true, 'ignoreUrls': true }],
			'no-array-constructor': 'error',
			'no-confusing-arrow': 'error',
			'no-else-return': ['error', { 'allowElseIf': false }],
			'no-extra-semi': 'error',
			'no-global-assign': 'error',
			'no-implicit-globals': 'error',
			'no-multiple-empty-lines': ['error', { 'max': 1, 'maxBOF': 0, 'maxEOF': 0 }],
			'no-multi-spaces': 'error',
			'no-new-object': 'error',
			'no-prototype-builtins': 'off',
			'no-spaced-func': 'error',
			'no-trailing-spaces': 'error',
			'no-undef': 'error',
			'no-unreachable': 'error',
			'no-unused-expressions': 'error',
			'no-unused-vars': ['error', { 'args': 'after-used' }],
			'no-var': 'error',
			'no-whitespace-before-property': 'error',
			'object-curly-spacing': ['error', 'always'],
			'object-shorthand': 'error',
			'one-var': ['error', 'never'],
			'prefer-arrow-callback': 'error',
			'prefer-rest-params': 'error',
			'quotes': ['error', 'single'],
			'semi': 'error',
			'space-before-blocks': 'error',
			'space-before-function-paren': ['error', { 'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always' }],
			'spaced-comment': ['error', 'always', {
				'line': {
					'exceptions': ['-', '+'],
					'markers': ['=', '!', '/'],
				},
				'block': {
					'exceptions': ['-', '+'],
					'markers': ['=', '!', ':', '::'],
					'balanced': true,
				},
			}],
			'space-infix-ops': 'error',
			'space-in-parens': ['error', 'never'],
			'space-unary-ops': ['error', { 'words': true, 'nonwords': false, 'overrides': {} }],
			'unicode-bom': ['error', 'never'],
		},
	},
];